### ISSUE TITLE
load balancer in front of both rpc and bootstrap is problematic

### ISSUE THREAD

**Issue by gregcusack** [anza-xyz/validator-lab#57]
if we don't pass in full-rpc then the load balancer may send an rpc request to the bootstrap and the request will fail. need to put load balancer just in front of RPC.

**Comment by gregcusack** [comment]
part of this issue is solved here: https://github.com/anza-xyz/validator-lab/pull/56

**Comment by gregcusack** [comment]
issue now is if you are in a bootstrap or validator node not running RPC, `-ul` will no longer work. Need to ping the load balancer endpoint

**Comment by CriesofCarrots** [comment]
> issue now is if you are in a bootstrap or validator node not running RPC, `-ul` will no longer work. Need to ping the load balancer endpoint

That might be a reason to run `solana config set -u <load_balancer_endpoint>` on boot

**Comment by gregcusack** [comment]
should be fixed in: https://github.com/anza-xyz/validator-lab/pull/63
